package net.earthcomputer.multiconnectintellij

object Constants {
    const val ARGUMENT = "net.earthcomputer.multiconnect.ap.Argument"
    const val DATAFIX = "net.earthcomputer.multiconnect.ap.Datafix"
    const val DEFAULT_CONSTRUCT = "net.earthcomputer.multiconnect.ap.DefaultConstruct"
    const val FILLED_ARGUMENT = "net.earthcomputer.multiconnect.ap.FilledArgument"
    const val FROM_REGISTRY = "net.earthcomputer.multiconnect.ap.FilledArgument.FromRegistry"
    const val INTRODUCE = "net.earthcomputer.multiconnect.ap.Introduce"
    const val HANDLER = "net.earthcomputer.multiconnect.ap.Handler"
    const val LENGTH = "net.earthcomputer.multiconnect.ap.Length"
    const val MESSAGE = "net.earthcomputer.multiconnect.ap.Message"
    const val MESSAGE_VARIANT = "net.earthcomputer.multiconnect.ap.MessageVariant"
    const val NETWORK_ENUM = "net.earthcomputer.multiconnect.ap.NetworkEnum"
    const val ONLY_IF = "net.earthcomputer.multiconnect.ap.OnlyIf"
    const val PARTIAL_HANDLER = "net.earthcomputer.multiconnect.ap.PartialHandler"
    const val POLYMORPHIC = "net.earthcomputer.multiconnect.ap.Polymorphic"
    const val POLYMORPHIC_BY = "net.earthcomputer.multiconnect.ap.PolymorphicBy"
    const val REGISTRY = "net.earthcomputer.multiconnect.ap.Registry"
    const val TYPE = "net.earthcomputer.multiconnect.ap.Type"

    const val FASTUTIL_INT_LIST = "it.unimi.dsi.fastutil.ints.IntList"
    const val FASTUTIL_LONG_LIST = "it.unimi.dsi.fastutil.longs.LongList"
    const val JAVA_UTIL_BIT_SET = "java.util.BitSet"
    const val JAVA_UTIL_FUNCTION_INT_FUNCTION = "java.util.function.IntFunction"
    const val JAVA_UTIL_FUNCTION_TO_INT_FUNCTION = "java.util.function.ToIntFunction"
    const val JAVA_UTIL_OPTIONAL_INT = "java.util.OptionalInt"
    const val JAVA_UTIL_OPTIONAL_LONG = "java.util.OptionalLong"
    const val JAVA_UTIL_UUID = "java.util.UUID"
    const val MINECRAFT_IDENTIFIER = "net.minecraft.util.Identifier"
    const val MINECRAFT_NBT_COMPOUND = "net.minecraft.nbt.NbtCompound"
    const val MINECRAFT_NETWORK_HANDLER = "net.minecraft.client.network.ClientPlayNetworkHandler"
    const val MULTICONNECT_DELAYED_PACKET_SENDER = "net.earthcomputer.multiconnect.impl.DelayedPacketSender"
    const val MULTICONNECT_TYPED_MAP = "net.earthcomputer.multiconnect.protocols.generic.TypedMap"
}
